=== devakumarv/online-counselling/others/appointments.dtd
<!ELEMENT appointments (appointment)>
  <!ATTLIST appointments id ID #REQUIRED>
  <!ELEMENT appointment (firstname,lastname,email,date,time,message)>
  <!ELEMENT firstname (#PCDATA) >
  <!ELEMENT lastname (#PCDATA)>
  <!ELEMENT email (#PCDATA)>
  <!ELEMENT date (#PCDATA)>
  <!ELEMENT time (#PCDATA)>
  <!ATTLIST appointment gender (M|F) #REQUIRED>
  <!ELEMENT message (#PCDATA)>
  <!ATTLIST appointment id ID #REQUIRED>

=== devakumarv/online-counselling/others/appointments.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE appointments SYSTEM "appointments.dtd"> <!--external dtd-->
<?xml-model href="appointments.xsd"?>
<appointments id="appointment1"> <!-- xml -->
    <appointment id="customer1" gender="M" >
      <firstname>abcd1</firstname>
      <lastname>efgh1</lastname>
      <email>devakumarv@hotmail.com</email>
      <date>2022-08-18</date>
      <time>09:00:00</time>
      <message>Hi Hello</message>
    </appointment>
</appointments>
