=== devakumarv/online-counselling/others/tutordetails.dtd
<!ELEMENT tutors (tutor)>
  <!ATTLIST tutors id ID #REQUIRED>
  <!ELEMENT tutor (firstname,lastname,email,dateofbirth,workexp,mobilenum,counsubject,streetadd,city,state,country,pincode)>
  <!ELEMENT firstname (#PCDATA)>
  <!ELEMENT lastname (#PCDATA)>
  <!ELEMENT email (#PCDATA)>
  <!ELEMENT dateofbirth (#PCDATA)>
  <!ATTLIST tutor gender (M|F) #REQUIRED>
  <!ELEMENT workexp (#PCDATA)>
  <!ELEMENT mobilenum (#PCDATA)>
  <!ELEMENT counsubject (#PCDATA)>
  <!ELEMENT streetadd (#PCDATA)>
  <!ELEMENT city (#PCDATA)>
  <!ELEMENT state (#PCDATA)>
  <!ELEMENT country (#PCDATA)>
  <!ELEMENT pincode (#PCDATA)>
  <!ATTLIST tutor id ID #REQUIRED>

=== devakumarv/online-counselling/others/tutordetails.xml
<?xml version="1.0" encoding="UTF-8"?> <!-- external dtd -->
<!DOCTYPE tutors SYSTEM "tutordetails.dtd">
<?xml-model href="tutordetails.xsd"?>
<tutors id="tutordet1"> <!-- xml -->
    <tutor id="tutor1" gender="M" >
      <firstname>abcd1</firstname>
      <lastname>efgh1</lastname>
      <email>devakumarv@hotmail.com</email>
      <dateofbirth>2022-08-18</dateofbirth>
      <workexp>4</workexp>
      <mobilenum>9445686329</mobilenum>
      <counsubject></counsubject>
      <streetadd>1/87, Krishnagiri</streetadd>
      <city>Krishnagiri</city>
      <state>Tamilnadu</state>
      <country>India</country>
      <pincode>635122</pincode>
    </tutor>
</tutors>
